# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 379448853ecb69dd83c9d2a0e951d09daf8fdb0fa2454be292e49cfcbf60cf356e03e021f9acef089eeb6260dd5a131ccf7c89157f3aaa059941a57b2c7c660c

test:
  secret_key_base: 6cea87ce56d7231fbe6cf3a2e731ed7353ccaf00067c656c20bd67de72c2c61d10aecbc752a314c4d96d2e09843e070eed45255d2b321591dc5ed5a7142a3217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
